#!/usr/bin/env node

/**
 * BMAD-METHOD Sample Application
 * 
 * This is a sample Node.js application demonstrating how to use
 * the BMAD-METHOD Universal AI Agent Framework for development.
 * 
 * The actual implementation would typically be generated by
 * BMAD agents based on your PRD and Architecture documents.
 */

console.log('🚀 BMAD-METHOD Sample Application');
console.log('===============================');
console.log('');
console.log('✨ This application was scaffolded using BMAD-METHOD');
console.log('📋 Next steps:');
console.log('   1. Create your PRD (Product Requirements Document)');
console.log('   2. Design your Architecture with AI agents');
console.log('   3. Generate development stories with Scrum Master');
console.log('   4. Implement features with Dev agent guidance');
console.log('   5. Validate with QA agent');
console.log('');
console.log('💡 Learn more: https://github.com/bmad-code-org/BMAD-METHOD');
console.log('💬 Join Discord: https://discord.gg/gk8jAdXWmj');
console.log('');

// Check if BMAD-METHOD is available
try {
  const { execSync } = require('child_process');
  const version = execSync('npx bmad-method --version', { encoding: 'utf8' }).trim();
  console.log(`🎯 BMAD-METHOD version: ${version}`);
} catch (error) {
  console.log('⚠️  BMAD-METHOD not found. Run: npm run bmad:setup');
}

console.log('');
console.log('🔧 Available npm scripts:');
console.log('   npm start     - Run this application');
console.log('   npm run dev   - Run with file watching');
console.log('   npm run bmad:setup  - Initialize BMAD-METHOD');
console.log('   npm run bmad:update - Update BMAD-METHOD');